[mypy]
warn_redundant_casts = True
warn_unused_ignores = True
disallow_any_generics = True
check_untyped_defs = True
implicit_reexport = False
disallow_untyped_defs = True
follow_imports = silent

[mypy-selenium.*]
ignore_missing_imports = True
